package uk.ac.aber.myapplication.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF740001) //deep red
val md_theme_light_onPrimary = Color(0xFFFFFFFF) // white
val md_theme_light_primaryContainer = Color(0xFFDAA520) // gold
val md_theme_light_onPrimaryContainer = Color(0xFF341100) // deep brown
val md_theme_light_secondary = Color(0xFFC0A080) // light gold
val md_theme_light_onSecondary = Color(0xFFFFFFFF) // white
val md_theme_light_secondaryContainer = Color(0xFFFFDBCB) //light gold
val md_theme_light_onSecondaryContainer = Color(0xFF2B160B) // deep brown
val md_theme_light_tertiary = Color(0xFF656031) // dark gold
val md_theme_light_onTertiary = Color(0xFFFFFFFF) // white
val md_theme_light_tertiaryContainer = Color(0xFFECE4AA) // light gold
val md_theme_light_onTertiaryContainer = Color(0xFF1F1C00) // deep brown
val md_theme_light_error = Color(0xFFBA1A1A) //deep red
val md_theme_light_errorContainer = Color(0xFFFFDAD6) // light red
val md_theme_light_onError = Color(0xFFFFFFFF) // white
val md_theme_light_onErrorContainer = Color(0xFF410002) // deep brown
val md_theme_light_background = Color(0xFFFFFBFF) // white
val md_theme_light_onBackground = Color(0xFF201A18) // deep brown
val md_theme_light_surface = Color(0xFFFFFBFF) // white
val md_theme_light_onSurface = Color(0xFF201A18) // deep brown
val md_theme_light_surfaceVariant = Color(0xFFDAA520) // light gold
val md_theme_light_onSurfaceVariant = Color(0xFF52443D) // deep brown
val md_theme_light_outline = Color(0xFF85736C) // goldish brown
val md_theme_light_inverseOnSurface = Color(0xFFFBEEE9) // light red
val md_theme_light_inverseSurface = Color(0xFF362F2C) // deep brown
val md_theme_light_inversePrimary = Color(0xFFDAA520) // gold
val md_theme_light_surfaceTint = Color(0xFF740001) // deep red

val md_theme_dark_primary = Color(0xFF0D6217) // dark green
val md_theme_dark_onPrimary = Color(0xFFFFFFFF) // white
val md_theme_dark_primaryContainer = Color(0xFF4A752C) // lighter green
val md_theme_dark_onPrimaryContainer = Color(0xFFD3D3D3) // light grey (silver)
val md_theme_dark_secondary = Color(0xFFC0C0C0) // silver
val md_theme_dark_onSecondary = Color(0xFF0D6217) // dark green
val md_theme_dark_secondaryContainer = Color(0xFF808080) // grey (darker silver)
val md_theme_dark_onSecondaryContainer = Color(0xFFD3D3D3) // light grey (silver)
val md_theme_dark_tertiary = Color(0xFF2E8B57) // sea green
val md_theme_dark_onTertiary = Color(0xFFFFFFFF) // white
val md_theme_dark_tertiaryContainer = Color(0xFF66CDAA) // medium aquamarine
val md_theme_dark_onTertiaryContainer = Color(0xFFD3D3D3) // light grey (silver)
val md_theme_dark_error = Color(0xFFFF0000) // red
val md_theme_dark_errorContainer = Color(0xFF8B0000) // dark red
val md_theme_dark_onError = Color(0xFFFFFFFF) // white
val md_theme_dark_onErrorContainer = Color(0xFFD3D3D3) // light grey (silver)
val md_theme_dark_background = Color(0xFF2F4F4F) // dark slate grey
val md_theme_dark_onBackground = Color(0xFFD3D3D3) // light grey (silver)
val md_theme_dark_surface = Color(0xFF2F4F4F) // dark slate grey
val md_theme_dark_onSurface = Color(0xFFD3D3D3) // light grey (silver)
val md_theme_dark_surfaceVariant = Color(0xFF696969) // dimgrey
val md_theme_dark_onSurfaceVariant = Color(0xFFD3D3D3) // light grey (silver)
val md_theme_dark_outline = Color(0xFFC0C0C0) // silver
val md_theme_dark_inverseOnSurface = Color(0xFF0D6217) // dark green
val md_theme_dark_inverseSurface = Color(0xFFD3D3D3) // light grey (silver)
val md_theme_dark_inversePrimary = Color(0xFFC0C0C0) // silver
val md_theme_dark_shadow = Color(0xFF000000) // black
val md_theme_dark_surfaceTint = Color(0xFF0D6217) // dark green
